/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ListingsRouteImport } from './routes/listings'
import { Route as HostRouteImport } from './routes/host'
import { Route as GuestRouteImport } from './routes/guest'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as BecomeHostRouteImport } from './routes/become-host'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ListingsListingIdRouteImport } from './routes/listings_.$listingId'
import { Route as HostReviewsRouteImport } from './routes/host.reviews'
import { Route as HostReservationsRouteImport } from './routes/host.reservations'
import { Route as HostMessagesRouteImport } from './routes/host.messages'
import { Route as HostEarningsRouteImport } from './routes/host.earnings'
import { Route as GuestTripsRouteImport } from './routes/guest.trips'
import { Route as GuestSavedRouteImport } from './routes/guest.saved'
import { Route as GuestMessagesRouteImport } from './routes/guest.messages'
import { Route as CheckoutListingIdRouteImport } from './routes/checkout.$listingId'
import { Route as AdminPayoutsRouteImport } from './routes/admin.payouts'
import { Route as AdminHostsRouteImport } from './routes/admin.hosts'
import { Route as AdminHostApprovalsRouteImport } from './routes/admin.host-approvals'
import { Route as AdminFinanceRouteImport } from './routes/admin.finance'
import { Route as AdminCouponsRouteImport } from './routes/admin.coupons'
import { Route as HostListingsIndexRouteImport } from './routes/host.listings.index'
import { Route as HostListingsNewRouteImport } from './routes/host.listings_.new'
import { Route as HostListingsListingIdRouteImport } from './routes/host.listings.$listingId'
import { Route as BookingsBookingIdConfirmationRouteImport } from './routes/bookings.$bookingId.confirmation'
import { Route as AdminHostsHostIdRouteImport } from './routes/admin.hosts_.$hostId'
import { Route as AdminListingsListingIdBookingsRouteImport } from './routes/admin.listings.$listingId.bookings'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsRoute = ListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => rootRouteImport,
} as any)
const HostRoute = HostRouteImport.update({
  id: '/host',
  path: '/host',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestRoute = GuestRouteImport.update({
  id: '/guest',
  path: '/guest',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeHostRoute = BecomeHostRouteImport.update({
  id: '/become-host',
  path: '/become-host',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsListingIdRoute = ListingsListingIdRouteImport.update({
  id: '/listings_/$listingId',
  path: '/listings/$listingId',
  getParentRoute: () => rootRouteImport,
} as any)
const HostReviewsRoute = HostReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => HostRoute,
} as any)
const HostReservationsRoute = HostReservationsRouteImport.update({
  id: '/reservations',
  path: '/reservations',
  getParentRoute: () => HostRoute,
} as any)
const HostMessagesRoute = HostMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => HostRoute,
} as any)
const HostEarningsRoute = HostEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => HostRoute,
} as any)
const GuestTripsRoute = GuestTripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => GuestRoute,
} as any)
const GuestSavedRoute = GuestSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => GuestRoute,
} as any)
const GuestMessagesRoute = GuestMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => GuestRoute,
} as any)
const CheckoutListingIdRoute = CheckoutListingIdRouteImport.update({
  id: '/checkout/$listingId',
  path: '/checkout/$listingId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPayoutsRoute = AdminPayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHostsRoute = AdminHostsRouteImport.update({
  id: '/hosts',
  path: '/hosts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHostApprovalsRoute = AdminHostApprovalsRouteImport.update({
  id: '/host-approvals',
  path: '/host-approvals',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanceRoute = AdminFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCouponsRoute = AdminCouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => AdminRoute,
} as any)
const HostListingsIndexRoute = HostListingsIndexRouteImport.update({
  id: '/listings/',
  path: '/listings/',
  getParentRoute: () => HostRoute,
} as any)
const HostListingsNewRoute = HostListingsNewRouteImport.update({
  id: '/listings_/new',
  path: '/listings/new',
  getParentRoute: () => HostRoute,
} as any)
const HostListingsListingIdRoute = HostListingsListingIdRouteImport.update({
  id: '/listings/$listingId',
  path: '/listings/$listingId',
  getParentRoute: () => HostRoute,
} as any)
const BookingsBookingIdConfirmationRoute =
  BookingsBookingIdConfirmationRouteImport.update({
    id: '/bookings/$bookingId/confirmation',
    path: '/bookings/$bookingId/confirmation',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminHostsHostIdRoute = AdminHostsHostIdRouteImport.update({
  id: '/hosts_/$hostId',
  path: '/hosts/$hostId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminListingsListingIdBookingsRoute =
  AdminListingsListingIdBookingsRouteImport.update({
    id: '/listings/$listingId/bookings',
    path: '/listings/$listingId/bookings',
    getParentRoute: () => AdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/become-host': typeof BecomeHostRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/guest': typeof GuestRouteWithChildren
  '/host': typeof HostRouteWithChildren
  '/listings': typeof ListingsRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/host-approvals': typeof AdminHostApprovalsRoute
  '/admin/hosts': typeof AdminHostsRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/checkout/$listingId': typeof CheckoutListingIdRoute
  '/guest/messages': typeof GuestMessagesRoute
  '/guest/saved': typeof GuestSavedRoute
  '/guest/trips': typeof GuestTripsRoute
  '/host/earnings': typeof HostEarningsRoute
  '/host/messages': typeof HostMessagesRoute
  '/host/reservations': typeof HostReservationsRoute
  '/host/reviews': typeof HostReviewsRoute
  '/listings/$listingId': typeof ListingsListingIdRoute
  '/admin/hosts/$hostId': typeof AdminHostsHostIdRoute
  '/bookings/$bookingId/confirmation': typeof BookingsBookingIdConfirmationRoute
  '/host/listings/$listingId': typeof HostListingsListingIdRoute
  '/host/listings/new': typeof HostListingsNewRoute
  '/host/listings/': typeof HostListingsIndexRoute
  '/admin/listings/$listingId/bookings': typeof AdminListingsListingIdBookingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/become-host': typeof BecomeHostRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/guest': typeof GuestRouteWithChildren
  '/host': typeof HostRouteWithChildren
  '/listings': typeof ListingsRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/host-approvals': typeof AdminHostApprovalsRoute
  '/admin/hosts': typeof AdminHostsRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/checkout/$listingId': typeof CheckoutListingIdRoute
  '/guest/messages': typeof GuestMessagesRoute
  '/guest/saved': typeof GuestSavedRoute
  '/guest/trips': typeof GuestTripsRoute
  '/host/earnings': typeof HostEarningsRoute
  '/host/messages': typeof HostMessagesRoute
  '/host/reservations': typeof HostReservationsRoute
  '/host/reviews': typeof HostReviewsRoute
  '/listings/$listingId': typeof ListingsListingIdRoute
  '/admin/hosts/$hostId': typeof AdminHostsHostIdRoute
  '/bookings/$bookingId/confirmation': typeof BookingsBookingIdConfirmationRoute
  '/host/listings/$listingId': typeof HostListingsListingIdRoute
  '/host/listings/new': typeof HostListingsNewRoute
  '/host/listings': typeof HostListingsIndexRoute
  '/admin/listings/$listingId/bookings': typeof AdminListingsListingIdBookingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/become-host': typeof BecomeHostRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/guest': typeof GuestRouteWithChildren
  '/host': typeof HostRouteWithChildren
  '/listings': typeof ListingsRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/host-approvals': typeof AdminHostApprovalsRoute
  '/admin/hosts': typeof AdminHostsRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/checkout/$listingId': typeof CheckoutListingIdRoute
  '/guest/messages': typeof GuestMessagesRoute
  '/guest/saved': typeof GuestSavedRoute
  '/guest/trips': typeof GuestTripsRoute
  '/host/earnings': typeof HostEarningsRoute
  '/host/messages': typeof HostMessagesRoute
  '/host/reservations': typeof HostReservationsRoute
  '/host/reviews': typeof HostReviewsRoute
  '/listings_/$listingId': typeof ListingsListingIdRoute
  '/admin/hosts_/$hostId': typeof AdminHostsHostIdRoute
  '/bookings/$bookingId/confirmation': typeof BookingsBookingIdConfirmationRoute
  '/host/listings/$listingId': typeof HostListingsListingIdRoute
  '/host/listings_/new': typeof HostListingsNewRoute
  '/host/listings/': typeof HostListingsIndexRoute
  '/admin/listings/$listingId/bookings': typeof AdminListingsListingIdBookingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/become-host'
    | '/forgot-password'
    | '/guest'
    | '/host'
    | '/listings'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/admin/coupons'
    | '/admin/finance'
    | '/admin/host-approvals'
    | '/admin/hosts'
    | '/admin/payouts'
    | '/checkout/$listingId'
    | '/guest/messages'
    | '/guest/saved'
    | '/guest/trips'
    | '/host/earnings'
    | '/host/messages'
    | '/host/reservations'
    | '/host/reviews'
    | '/listings/$listingId'
    | '/admin/hosts/$hostId'
    | '/bookings/$bookingId/confirmation'
    | '/host/listings/$listingId'
    | '/host/listings/new'
    | '/host/listings/'
    | '/admin/listings/$listingId/bookings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/become-host'
    | '/forgot-password'
    | '/guest'
    | '/host'
    | '/listings'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/admin/coupons'
    | '/admin/finance'
    | '/admin/host-approvals'
    | '/admin/hosts'
    | '/admin/payouts'
    | '/checkout/$listingId'
    | '/guest/messages'
    | '/guest/saved'
    | '/guest/trips'
    | '/host/earnings'
    | '/host/messages'
    | '/host/reservations'
    | '/host/reviews'
    | '/listings/$listingId'
    | '/admin/hosts/$hostId'
    | '/bookings/$bookingId/confirmation'
    | '/host/listings/$listingId'
    | '/host/listings/new'
    | '/host/listings'
    | '/admin/listings/$listingId/bookings'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/become-host'
    | '/forgot-password'
    | '/guest'
    | '/host'
    | '/listings'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/admin/coupons'
    | '/admin/finance'
    | '/admin/host-approvals'
    | '/admin/hosts'
    | '/admin/payouts'
    | '/checkout/$listingId'
    | '/guest/messages'
    | '/guest/saved'
    | '/guest/trips'
    | '/host/earnings'
    | '/host/messages'
    | '/host/reservations'
    | '/host/reviews'
    | '/listings_/$listingId'
    | '/admin/hosts_/$hostId'
    | '/bookings/$bookingId/confirmation'
    | '/host/listings/$listingId'
    | '/host/listings_/new'
    | '/host/listings/'
    | '/admin/listings/$listingId/bookings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  BecomeHostRoute: typeof BecomeHostRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  GuestRoute: typeof GuestRouteWithChildren
  HostRoute: typeof HostRouteWithChildren
  ListingsRoute: typeof ListingsRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  CheckoutListingIdRoute: typeof CheckoutListingIdRoute
  ListingsListingIdRoute: typeof ListingsListingIdRoute
  BookingsBookingIdConfirmationRoute: typeof BookingsBookingIdConfirmationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings': {
      id: '/listings'
      path: '/listings'
      fullPath: '/listings'
      preLoaderRoute: typeof ListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host': {
      id: '/host'
      path: '/host'
      fullPath: '/host'
      preLoaderRoute: typeof HostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guest': {
      id: '/guest'
      path: '/guest'
      fullPath: '/guest'
      preLoaderRoute: typeof GuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-host': {
      id: '/become-host'
      path: '/become-host'
      fullPath: '/become-host'
      preLoaderRoute: typeof BecomeHostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings_/$listingId': {
      id: '/listings_/$listingId'
      path: '/listings/$listingId'
      fullPath: '/listings/$listingId'
      preLoaderRoute: typeof ListingsListingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/reviews': {
      id: '/host/reviews'
      path: '/reviews'
      fullPath: '/host/reviews'
      preLoaderRoute: typeof HostReviewsRouteImport
      parentRoute: typeof HostRoute
    }
    '/host/reservations': {
      id: '/host/reservations'
      path: '/reservations'
      fullPath: '/host/reservations'
      preLoaderRoute: typeof HostReservationsRouteImport
      parentRoute: typeof HostRoute
    }
    '/host/messages': {
      id: '/host/messages'
      path: '/messages'
      fullPath: '/host/messages'
      preLoaderRoute: typeof HostMessagesRouteImport
      parentRoute: typeof HostRoute
    }
    '/host/earnings': {
      id: '/host/earnings'
      path: '/earnings'
      fullPath: '/host/earnings'
      preLoaderRoute: typeof HostEarningsRouteImport
      parentRoute: typeof HostRoute
    }
    '/guest/trips': {
      id: '/guest/trips'
      path: '/trips'
      fullPath: '/guest/trips'
      preLoaderRoute: typeof GuestTripsRouteImport
      parentRoute: typeof GuestRoute
    }
    '/guest/saved': {
      id: '/guest/saved'
      path: '/saved'
      fullPath: '/guest/saved'
      preLoaderRoute: typeof GuestSavedRouteImport
      parentRoute: typeof GuestRoute
    }
    '/guest/messages': {
      id: '/guest/messages'
      path: '/messages'
      fullPath: '/guest/messages'
      preLoaderRoute: typeof GuestMessagesRouteImport
      parentRoute: typeof GuestRoute
    }
    '/checkout/$listingId': {
      id: '/checkout/$listingId'
      path: '/checkout/$listingId'
      fullPath: '/checkout/$listingId'
      preLoaderRoute: typeof CheckoutListingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/payouts': {
      id: '/admin/payouts'
      path: '/payouts'
      fullPath: '/admin/payouts'
      preLoaderRoute: typeof AdminPayoutsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/hosts': {
      id: '/admin/hosts'
      path: '/hosts'
      fullPath: '/admin/hosts'
      preLoaderRoute: typeof AdminHostsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/host-approvals': {
      id: '/admin/host-approvals'
      path: '/host-approvals'
      fullPath: '/admin/host-approvals'
      preLoaderRoute: typeof AdminHostApprovalsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/finance': {
      id: '/admin/finance'
      path: '/finance'
      fullPath: '/admin/finance'
      preLoaderRoute: typeof AdminFinanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/coupons': {
      id: '/admin/coupons'
      path: '/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AdminCouponsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/host/listings/': {
      id: '/host/listings/'
      path: '/listings'
      fullPath: '/host/listings/'
      preLoaderRoute: typeof HostListingsIndexRouteImport
      parentRoute: typeof HostRoute
    }
    '/host/listings_/new': {
      id: '/host/listings_/new'
      path: '/listings/new'
      fullPath: '/host/listings/new'
      preLoaderRoute: typeof HostListingsNewRouteImport
      parentRoute: typeof HostRoute
    }
    '/host/listings/$listingId': {
      id: '/host/listings/$listingId'
      path: '/listings/$listingId'
      fullPath: '/host/listings/$listingId'
      preLoaderRoute: typeof HostListingsListingIdRouteImport
      parentRoute: typeof HostRoute
    }
    '/bookings/$bookingId/confirmation': {
      id: '/bookings/$bookingId/confirmation'
      path: '/bookings/$bookingId/confirmation'
      fullPath: '/bookings/$bookingId/confirmation'
      preLoaderRoute: typeof BookingsBookingIdConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/hosts_/$hostId': {
      id: '/admin/hosts_/$hostId'
      path: '/hosts/$hostId'
      fullPath: '/admin/hosts/$hostId'
      preLoaderRoute: typeof AdminHostsHostIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/listings/$listingId/bookings': {
      id: '/admin/listings/$listingId/bookings'
      path: '/listings/$listingId/bookings'
      fullPath: '/admin/listings/$listingId/bookings'
      preLoaderRoute: typeof AdminListingsListingIdBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCouponsRoute: typeof AdminCouponsRoute
  AdminFinanceRoute: typeof AdminFinanceRoute
  AdminHostApprovalsRoute: typeof AdminHostApprovalsRoute
  AdminHostsRoute: typeof AdminHostsRoute
  AdminPayoutsRoute: typeof AdminPayoutsRoute
  AdminHostsHostIdRoute: typeof AdminHostsHostIdRoute
  AdminListingsListingIdBookingsRoute: typeof AdminListingsListingIdBookingsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCouponsRoute: AdminCouponsRoute,
  AdminFinanceRoute: AdminFinanceRoute,
  AdminHostApprovalsRoute: AdminHostApprovalsRoute,
  AdminHostsRoute: AdminHostsRoute,
  AdminPayoutsRoute: AdminPayoutsRoute,
  AdminHostsHostIdRoute: AdminHostsHostIdRoute,
  AdminListingsListingIdBookingsRoute: AdminListingsListingIdBookingsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface GuestRouteChildren {
  GuestMessagesRoute: typeof GuestMessagesRoute
  GuestSavedRoute: typeof GuestSavedRoute
  GuestTripsRoute: typeof GuestTripsRoute
}

const GuestRouteChildren: GuestRouteChildren = {
  GuestMessagesRoute: GuestMessagesRoute,
  GuestSavedRoute: GuestSavedRoute,
  GuestTripsRoute: GuestTripsRoute,
}

const GuestRouteWithChildren = GuestRoute._addFileChildren(GuestRouteChildren)

interface HostRouteChildren {
  HostEarningsRoute: typeof HostEarningsRoute
  HostMessagesRoute: typeof HostMessagesRoute
  HostReservationsRoute: typeof HostReservationsRoute
  HostReviewsRoute: typeof HostReviewsRoute
  HostListingsListingIdRoute: typeof HostListingsListingIdRoute
  HostListingsNewRoute: typeof HostListingsNewRoute
  HostListingsIndexRoute: typeof HostListingsIndexRoute
}

const HostRouteChildren: HostRouteChildren = {
  HostEarningsRoute: HostEarningsRoute,
  HostMessagesRoute: HostMessagesRoute,
  HostReservationsRoute: HostReservationsRoute,
  HostReviewsRoute: HostReviewsRoute,
  HostListingsListingIdRoute: HostListingsListingIdRoute,
  HostListingsNewRoute: HostListingsNewRoute,
  HostListingsIndexRoute: HostListingsIndexRoute,
}

const HostRouteWithChildren = HostRoute._addFileChildren(HostRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  BecomeHostRoute: BecomeHostRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  GuestRoute: GuestRouteWithChildren,
  HostRoute: HostRouteWithChildren,
  ListingsRoute: ListingsRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  CheckoutListingIdRoute: CheckoutListingIdRoute,
  ListingsListingIdRoute: ListingsListingIdRoute,
  BookingsBookingIdConfirmationRoute: BookingsBookingIdConfirmationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
